### ISSUE TITLE
Excuse Me?

### ISSUE THREAD

**Issue by Donastria** [Lortseam/completeconfig#29]

**Comment by Donastria** [comment]
So tell me something. How is it that a 1.20.1 version of Custom Portals takes a 1.20.4 version of CompleteConfig???  Someone has their lines crossed...

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'CompleteConfig' (completeconfig) 2.5.0 with version 2.5.2 or later.
More details:
	 - Mod 'Custom Portals' (customportals) 3.3.1 requires version 2.5.2 or later of mod 'CompleteConfig' (completeconfig), but only the wrong version is present: 2.5.0!

**Comment by Lortseam** [comment]
Please ask the developer of Custom Portals, I cannot do anything about that.

**Comment by ghost** [comment]
Custom Portals dev here. Despite CompleteConfig 2.5.2 not listing 1.20.1 as a compatible version, I've verified that it does in fact work on 1.20.1. Custom Portals requires it because prior versions contain a compatibility issue with newer versions of the Fabric loader.

Regardless this is now moot because I've released a new version of Custom Portals for 1.20.1 that replaces CompleteConfig with YACL.
